/**
 * Model class representing a single semantic text chunk of a legal document
 * designed for pgvector database matching.
 */
export class LegalChunk {
  /**
   * @param {number} id - Autogenerated ID.
   * @param {string} documentId - Foreign key referencing the parent Document UUID.
   * @param {string} content - Raw text content string of the chunk.
   * @param {string|null} sectionHeader - The closest preceding heading tracking tag (h1-h4).
   * @param {number} chunkIndex - Order sequence index of the chunk.
   * @param {Array<number>|null} [embedding=null] - 768-dimension float array vector from Google gemini-embedding-001.
   */
  constructor(id, documentId, content, sectionHeader, chunkIndex, embedding = null) {
    this.id = id;
    this.documentId = documentId;
    this.content = content;
    this.sectionHeader = sectionHeader;
    this.chunkIndex = chunkIndex;
    this.embedding = embedding;
  }
}
